"use strict";
// UI strings. English is the base; any key missing from another language falls back to English
// (see tr() in app.js). en/bn/hi are complete. The other eight cover the core screens only and
// should be reviewed by native speakers. Scheme names are never translated.
window.STRINGS = {
  en: {
    siteDisclaimer: "Independent project: this is not a government website and is not affiliated with any government body. Results are eligibility guidance, not an official determination. Always verify current requirements on the official source linked for each scheme.",
    aiBusy: "The AI service is busy right now. Please wait a minute and try again.",
    tooMany: "Too many requests from your connection. Please wait a moment and try again.",
    title: "Find Government Schemes You May Qualify For",
    sub: "Tell us about yourself by typing or speaking. We turn it into an eligibility map.",
    chooseLang: "Choose your language",
    label: "Describe your situation", ph: "Type your situation…",
    speak: "🎤 Speak", stop: "⏹ Stop", go: "Find my schemes", working: "Checking schemes…",
    examples: ["I am a farmer from West Bengal. I own 2 acres of land. I have Aadhaar and a bank account.",
      "I am a student from Bihar.", "I am a woman from West Bengal, 35 years old.", "My family income is 2 lakh rupees a year."],
    exLabels: ["I am a farmer from West Bengal…", "I am a student from Bihar…", "I am a woman from West Bengal…", "My family income is…"],
    profile: "YOUR PROFILE", map: "YOUR ELIGIBILITY MAP", docs: "DOCUMENTS YOU MAY NEED",
    followup: "A few quick questions",
    updateTitle: "Add or correct your details", updateHint: "This adds to the profile above. To start over instead, use the main box at the top.",
    updateGo: "Update my profile", updatePh: "e.g. My land is actually 5 acres…", answerLabel: "Your answers or corrections",
    status: { ELIGIBLE: "Eligible", LIKELY_ELIGIBLE: "Likely eligible", MISSING_INFORMATION: "More information needed", NOT_ELIGIBLE: "Not eligible" },
    why: "Why?", matched: "Conditions met", notMet: "Conditions not met", confirm: "To confirm", missing: "Information needed",
    docsNeeded: "Documents needed", verify: "Verify official information ↗", verified: "Last verified",
    forSchemes: "Needed for", yes: "Yes", no: "No", err: "Something went wrong. Please try again.",
    aiDown: "AI service is temporarily unavailable. Please try again or use English mode.",
    aiFallback: "AI service is temporarily unavailable. Showing basic explanations in English.",
    aiPartial: "Some explanations could not be translated and are shown in English.",
    aiOfflineReader: "AI service is temporarily unavailable. Using a basic English-only reader for your text.",
    reason: "Reason",
    noSR: "Voice input is not available in this browser. You can type instead.",
    voiceUnsupported: "Voice input is not supported for this language in your browser. You can type instead.",
    micDenied: "Microphone access was blocked. Allow it in the browser, or type instead.",
    micMissing: "No microphone was found. You can type instead.",
    voiceNoResult: "No speech was captured. If this keeps happening, your browser may not support voice input for this language. You can type instead.",
    voiceError: "Voice input failed. You can type instead.",
    listening: "Listening… speak now.", readAloud: "🔊 Read aloud", stopReading: "⏹ Stop reading",
    noVoice: "This browser has no voice installed for this language, so read-aloud is unavailable. The text is shown on screen.",
    speechFailed: "Read-aloud failed to start.",
    fields: { state: "State", occupation: "Occupation", age: "Age", gender: "Gender", land_area_acres: "Land (acres)",
      land_ownership: "Land ownership", crop: "Crop", annual_family_income: "Family income (₹/year)",
      has_aadhaar: "Aadhaar", has_bank_account: "Bank account", is_income_taxpayer: "Pays income tax",
      is_govt_employee: "Govt employee/pensioner in family" },
  },
  bn: {
    siteDisclaimer: "এটি একটি স্বাধীন প্রকল্প: কোনো সরকারি ওয়েবসাইট নয় এবং কোনো সরকারি সংস্থার সঙ্গে যুক্ত নয়। ফলাফল কেবল যোগ্যতার দিকনির্দেশনা, সরকারি সিদ্ধান্ত নয়। প্রতিটি প্রকল্পের জন্য দেওয়া সরকারি সূত্রে সর্বশেষ শর্ত অবশ্যই যাচাই করুন।",
    aiBusy: "AI পরিষেবা এখন ব্যস্ত। এক মিনিট অপেক্ষা করে আবার চেষ্টা করুন।",
    tooMany: "আপনার সংযোগ থেকে অনেক বেশি অনুরোধ এসেছে। একটু অপেক্ষা করে আবার চেষ্টা করুন।",
    title: "যে সরকারি প্রকল্পগুলির জন্য আপনি যোগ্য হতে পারেন তা খুঁজুন",
    sub: "লিখে বা বলে আপনার অবস্থা জানান। আমরা তা থেকে যোগ্যতার মানচিত্র তৈরি করব।",
    chooseLang: "আপনার ভাষা বেছে নিন",
    label: "আপনার অবস্থা লিখুন", ph: "আপনার অবস্থা লিখুন…",
    speak: "🎤 বলুন", stop: "⏹ থামুন", go: "আমার প্রকল্প খুঁজুন", working: "প্রকল্প যাচাই করা হচ্ছে…",
    examples: ["আমি পশ্চিমবঙ্গের একজন কৃষক। আমার ২ একর জমি আছে। আমার আধার ও ব্যাংক অ্যাকাউন্ট আছে।",
      "আমি বিহারের একজন ছাত্র।", "আমি পশ্চিমবঙ্গের একজন মহিলা, বয়স ৩৫।", "আমার পরিবারের বার্ষিক আয় ২ লক্ষ টাকা।"],
    exLabels: ["আমি পশ্চিমবঙ্গের একজন কৃষক…", "আমি বিহারের একজন ছাত্র…", "আমি পশ্চিমবঙ্গের একজন মহিলা…", "আমার পরিবারের আয়…"],
    profile: "আপনার তথ্য", map: "আপনার যোগ্যতার মানচিত্র", docs: "যে নথিগুলি লাগতে পারে",
    followup: "কয়েকটি ছোট প্রশ্ন",
    updateTitle: "তথ্য যোগ বা সংশোধন করুন", updateHint: "এটি উপরের তথ্যের সঙ্গে যোগ হবে। নতুন করে শুরু করতে উপরের মূল বাক্সটি ব্যবহার করুন।",
    updateGo: "আমার তথ্য হালনাগাদ করুন", updatePh: "যেমন: আমার জমি আসলে ৫ একর…", answerLabel: "আপনার উত্তর বা সংশোধন",
    status: { ELIGIBLE: "যোগ্য", LIKELY_ELIGIBLE: "সম্ভবত যোগ্য", MISSING_INFORMATION: "আরও তথ্য দরকার", NOT_ELIGIBLE: "যোগ্য নন" },
    why: "কেন?", matched: "যে শর্ত পূরণ হয়েছে", notMet: "যে শর্ত পূরণ হয়নি", confirm: "যাচাই করতে হবে", missing: "প্রয়োজনীয় তথ্য",
    docsNeeded: "প্রয়োজনীয় নথি", verify: "সরকারি তথ্য যাচাই করুন ↗", verified: "সর্বশেষ যাচাই",
    forSchemes: "যে প্রকল্পের জন্য", yes: "হ্যাঁ", no: "না", err: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
    aiDown: "AI পরিষেবা সাময়িকভাবে পাওয়া যাচ্ছে না। অনুগ্রহ করে আবার চেষ্টা করুন বা ইংরেজি ব্যবহার করুন।",
    aiFallback: "AI পরিষেবা সাময়িকভাবে পাওয়া যাচ্ছে না। সহজ ব্যাখ্যা ইংরেজিতে দেখানো হচ্ছে।",
    aiPartial: "কিছু ব্যাখ্যা অনুবাদ করা যায়নি, সেগুলি ইংরেজিতে দেখানো হচ্ছে।",
    reason: "কারণ",
    noSR: "এই ব্রাউজারে ভয়েস ইনপুট নেই। আপনি লিখতে পারেন।",
    voiceUnsupported: "আপনার ব্রাউজারে এই ভাষার জন্য ভয়েস ইনপুট সমর্থিত নয়। আপনি লিখতে পারেন।",
    micDenied: "মাইক্রোফোনের অনুমতি বন্ধ আছে। ব্রাউজারে অনুমতি দিন, অথবা লিখুন।",
    micMissing: "কোনো মাইক্রোফোন পাওয়া যায়নি। আপনি লিখতে পারেন।",
    voiceNoResult: "কোনো কথা ধরা পড়েনি। বারবার হলে আপনার ব্রাউজার এই ভাষার ভয়েস ইনপুট সমর্থন নাও করতে পারে। আপনি লিখতে পারেন।",
    voiceError: "ভয়েস ইনপুট কাজ করেনি। আপনি লিখতে পারেন।",
    listening: "শুনছি… বলুন।", readAloud: "🔊 পড়ে শোনান", stopReading: "⏹ পড়া থামান",
    noVoice: "এই ব্রাউজারে এই ভাষার কোনো ভয়েস ইনস্টল করা নেই, তাই পড়ে শোনানো সম্ভব নয়। লেখা পর্দায় দেখানো হয়েছে।",
    speechFailed: "পড়ে শোনানো শুরু হয়নি।",
    fields: { state: "রাজ্য", occupation: "পেশা", age: "বয়স", gender: "লিঙ্গ", land_area_acres: "জমি (একর)",
      land_ownership: "জমির মালিকানা", crop: "ফসল", annual_family_income: "পারিবারিক আয় (₹/বছর)",
      has_aadhaar: "আধার", has_bank_account: "ব্যাংক অ্যাকাউন্ট", is_income_taxpayer: "আয়কর দেন",
      is_govt_employee: "পরিবারে সরকারি কর্মচারী/পেনশনভোগী" },
  },
  hi: {
    siteDisclaimer: "यह एक स्वतंत्र प्रोजेक्ट है: यह कोई सरकारी वेबसाइट नहीं है और किसी सरकारी संस्था से जुड़ा नहीं है। परिणाम केवल पात्रता का मार्गदर्शन हैं, कोई आधिकारिक निर्णय नहीं। हर योजना के लिए दिए गए आधिकारिक स्रोत पर नवीनतम शर्तें ज़रूर जाँचें।",
    aiBusy: "AI सेवा अभी व्यस्त है। कृपया एक मिनट रुककर दोबारा कोशिश करें।",
    tooMany: "आपके कनेक्शन से बहुत अधिक अनुरोध आए हैं। कृपया थोड़ी देर रुककर दोबारा कोशिश करें।",
    title: "जानिए किन सरकारी योजनाओं के लिए आप पात्र हो सकते हैं",
    sub: "लिखकर या बोलकर अपनी स्थिति बताइए। हम उससे पात्रता का नक्शा बनाएँगे।",
    chooseLang: "अपनी भाषा चुनें",
    label: "अपनी स्थिति बताइए", ph: "अपनी स्थिति लिखिए…",
    speak: "🎤 बोलिए", stop: "⏹ रोकें", go: "मेरी योजनाएँ खोजें", working: "योजनाएँ जाँची जा रही हैं…",
    examples: ["मैं पश्चिम बंगाल का किसान हूँ। मेरे पास 2 एकड़ ज़मीन है। मेरे पास आधार और बैंक खाता है।",
      "मैं बिहार का छात्र हूँ।", "मैं पश्चिम बंगाल की महिला हूँ, उम्र 35 वर्ष।", "मेरे परिवार की सालाना आय 2 लाख रुपये है।"],
    exLabels: ["मैं पश्चिम बंगाल का किसान हूँ…", "मैं बिहार का छात्र हूँ…", "मैं पश्चिम बंगाल की महिला हूँ…", "मेरे परिवार की आय…"],
    profile: "आपकी जानकारी", map: "आपकी पात्रता का नक्शा", docs: "ज़रूरी हो सकने वाले दस्तावेज़",
    followup: "कुछ छोटे सवाल",
    updateTitle: "जानकारी जोड़ें या सुधारें", updateHint: "यह ऊपर की जानकारी में जुड़ेगा। नए सिरे से शुरू करने के लिए ऊपर का मुख्य बॉक्स इस्तेमाल करें।",
    updateGo: "मेरी जानकारी अपडेट करें", updatePh: "जैसे: मेरी ज़मीन असल में 5 एकड़ है…", answerLabel: "आपके जवाब या सुधार",
    status: { ELIGIBLE: "पात्र", LIKELY_ELIGIBLE: "संभवतः पात्र", MISSING_INFORMATION: "और जानकारी चाहिए", NOT_ELIGIBLE: "पात्र नहीं" },
    why: "क्यों?", matched: "पूरी हुई शर्तें", notMet: "पूरी न हुई शर्तें", confirm: "पुष्टि करनी है", missing: "ज़रूरी जानकारी",
    docsNeeded: "ज़रूरी दस्तावेज़", verify: "सरकारी जानकारी जाँचें ↗", verified: "अंतिम जाँच",
    forSchemes: "इन योजनाओं के लिए", yes: "हाँ", no: "नहीं", err: "कुछ गड़बड़ हुई। कृपया दोबारा कोशिश करें।",
    aiDown: "AI सेवा अस्थायी रूप से उपलब्ध नहीं है। कृपया दोबारा कोशिश करें या अंग्रेज़ी इस्तेमाल करें।",
    aiFallback: "AI सेवा अस्थायी रूप से उपलब्ध नहीं है। सरल स्पष्टीकरण अंग्रेज़ी में दिखाए जा रहे हैं।",
    aiPartial: "कुछ स्पष्टीकरण अनुवादित नहीं हो सके, वे अंग्रेज़ी में दिखाए गए हैं।",
    reason: "कारण",
    noSR: "इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं है। आप लिखकर बता सकते हैं।",
    voiceUnsupported: "आपके ब्राउज़र में इस भाषा के लिए वॉइस इनपुट समर्थित नहीं है। आप लिखकर बता सकते हैं।",
    micDenied: "माइक्रोफ़ोन की अनुमति बंद है। ब्राउज़र में अनुमति दें, या लिखकर बताएँ।",
    micMissing: "कोई माइक्रोफ़ोन नहीं मिला। आप लिखकर बता सकते हैं।",
    voiceNoResult: "कोई आवाज़ दर्ज नहीं हुई। बार-बार होने पर हो सकता है आपका ब्राउज़र इस भाषा के वॉइस इनपुट को समर्थन न देता हो। आप लिखकर बता सकते हैं।",
    voiceError: "वॉइस इनपुट काम नहीं किया। आप लिखकर बता सकते हैं।",
    listening: "सुन रहे हैं… बोलिए।", readAloud: "🔊 पढ़कर सुनाएँ", stopReading: "⏹ पढ़ना रोकें",
    noVoice: "इस ब्राउज़र में इस भाषा की कोई आवाज़ इंस्टॉल नहीं है, इसलिए पढ़कर सुनाना संभव नहीं। पाठ स्क्रीन पर दिखाया गया है।",
    speechFailed: "पढ़कर सुनाना शुरू नहीं हुआ।",
    fields: { state: "राज्य", occupation: "पेशा", age: "उम्र", gender: "लिंग", land_area_acres: "ज़मीन (एकड़)",
      land_ownership: "ज़मीन का मालिकाना", crop: "फसल", annual_family_income: "पारिवारिक आय (₹/वर्ष)",
      has_aadhaar: "आधार", has_bank_account: "बैंक खाता", is_income_taxpayer: "आयकर देते हैं",
      is_govt_employee: "परिवार में सरकारी कर्मचारी/पेंशनर" },
  },
  // ---- core-screen translations only; everything else falls back to English ----
  mr: {
    title: "तुम्ही कोणत्या सरकारी योजनांसाठी पात्र असू शकता ते शोधा", chooseLang: "तुमची भाषा निवडा",
    label: "तुमची परिस्थिती सांगा", ph: "तुमची परिस्थिती लिहा…",
    speak: "🎤 बोला", stop: "⏹ थांबा", go: "माझ्या योजना शोधा", working: "योजना तपासत आहोत…",
    profile: "तुमची माहिती", map: "तुमच्या पात्रतेचा नकाशा", docs: "लागू शकणारी कागदपत्रे",
    status: { ELIGIBLE: "पात्र", LIKELY_ELIGIBLE: "कदाचित पात्र", MISSING_INFORMATION: "अधिक माहिती हवी", NOT_ELIGIBLE: "पात्र नाही" },
    why: "का?", docsNeeded: "आवश्यक कागदपत्रे", verify: "अधिकृत माहिती तपासा ↗", followup: "काही छोटे प्रश्न",
    aiDown: "AI सेवा तात्पुरती उपलब्ध नाही. कृपया पुन्हा प्रयत्न करा किंवा इंग्रजी वापरा.",
  },
  te: {
    title: "మీరు అర్హత పొందగల ప్రభుత్వ పథకాలను కనుగొనండి", chooseLang: "మీ భాషను ఎంచుకోండి",
    label: "మీ పరిస్థితిని చెప్పండి", ph: "మీ పరిస్థితిని రాయండి…",
    speak: "🎤 మాట్లాడండి", stop: "⏹ ఆపండి", go: "నా పథకాలను కనుగొనండి", working: "పథకాలను పరిశీలిస్తున్నాం…",
    profile: "మీ వివరాలు", map: "మీ అర్హత పటం", docs: "అవసరమయ్యే పత్రాలు",
    status: { ELIGIBLE: "అర్హులు", LIKELY_ELIGIBLE: "బహుశా అర్హులు", MISSING_INFORMATION: "మరింత సమాచారం కావాలి", NOT_ELIGIBLE: "అర్హులు కారు" },
    why: "ఎందుకు?", docsNeeded: "అవసరమైన పత్రాలు", verify: "అధికారిక సమాచారం తనిఖీ చేయండి ↗", followup: "కొన్ని చిన్న ప్రశ్నలు",
    aiDown: "AI సేవ తాత్కాలికంగా అందుబాటులో లేదు. దయచేసి మళ్లీ ప్రయత్నించండి లేదా ఇంగ్లీష్ ఉపయోగించండి.",
  },
  ta: {
    title: "நீங்கள் தகுதி பெறக்கூடிய அரசு திட்டங்களைக் கண்டறியுங்கள்", chooseLang: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    label: "உங்கள் நிலையைச் சொல்லுங்கள்", ph: "உங்கள் நிலையை எழுதுங்கள்…",
    speak: "🎤 பேசுங்கள்", stop: "⏹ நிறுத்து", go: "என் திட்டங்களைத் தேடு", working: "திட்டங்களைச் சரிபார்க்கிறோம்…",
    profile: "உங்கள் விவரங்கள்", map: "உங்கள் தகுதி வரைபடம்", docs: "தேவைப்படக்கூடிய ஆவணங்கள்",
    status: { ELIGIBLE: "தகுதி உள்ளது", LIKELY_ELIGIBLE: "தகுதி இருக்கலாம்", MISSING_INFORMATION: "கூடுதல் தகவல் தேவை", NOT_ELIGIBLE: "தகுதி இல்லை" },
    why: "ஏன்?", docsNeeded: "தேவையான ஆவணங்கள்", verify: "அதிகாரப்பூர்வ தகவலைச் சரிபார்க்கவும் ↗", followup: "சில சிறிய கேள்விகள்",
    aiDown: "AI சேவை தற்காலிகமாகக் கிடைக்கவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது ஆங்கிலத்தைப் பயன்படுத்தவும்.",
  },
  gu: {
    title: "તમે કઈ સરકારી યોજનાઓ માટે પાત્ર હોઈ શકો તે શોધો", chooseLang: "તમારી ભાષા પસંદ કરો",
    label: "તમારી પરિસ્થિતિ જણાવો", ph: "તમારી પરિસ્થિતિ લખો…",
    speak: "🎤 બોલો", stop: "⏹ બંધ કરો", go: "મારી યોજનાઓ શોધો", working: "યોજનાઓ તપાસી રહ્યા છીએ…",
    profile: "તમારી માહિતી", map: "તમારી પાત્રતાનો નકશો", docs: "જરૂર પડી શકે તેવા દસ્તાવેજો",
    status: { ELIGIBLE: "પાત્ર", LIKELY_ELIGIBLE: "કદાચ પાત્ર", MISSING_INFORMATION: "વધુ માહિતી જોઈએ", NOT_ELIGIBLE: "પાત્ર નથી" },
    why: "શા માટે?", docsNeeded: "જરૂરી દસ્તાવેજો", verify: "સત્તાવાર માહિતી ચકાસો ↗", followup: "થોડા નાના પ્રશ્નો",
    aiDown: "AI સેવા હાલ ઉપલબ્ધ નથી. કૃપા કરીને ફરી પ્રયાસ કરો અથવા અંગ્રેજીનો ઉપયોગ કરો.",
  },
  ur: {
    title: "وہ سرکاری اسکیمیں تلاش کریں جن کے آپ اہل ہو سکتے ہیں", chooseLang: "اپنی زبان منتخب کریں",
    label: "اپنی صورتحال بتائیں", ph: "اپنی صورتحال لکھیں…",
    speak: "🎤 بولیں", stop: "⏹ روکیں", go: "میری اسکیمیں تلاش کریں", working: "اسکیمیں جانچی جا رہی ہیں…",
    profile: "آپ کی معلومات", map: "آپ کی اہلیت کا نقشہ", docs: "ممکنہ ضروری دستاویزات",
    status: { ELIGIBLE: "اہل", LIKELY_ELIGIBLE: "غالباً اہل", MISSING_INFORMATION: "مزید معلومات درکار", NOT_ELIGIBLE: "اہل نہیں" },
    why: "کیوں؟", docsNeeded: "ضروری دستاویزات", verify: "سرکاری معلومات کی تصدیق کریں ↗", followup: "کچھ مختصر سوالات",
    aiDown: "AI سروس عارضی طور پر دستیاب نہیں۔ براہ کرم دوبارہ کوشش کریں یا انگریزی استعمال کریں۔",
  },
  kn: {
    title: "ನೀವು ಅರ್ಹರಾಗಬಹುದಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ", chooseLang: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    label: "ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಯನ್ನು ತಿಳಿಸಿ", ph: "ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಯನ್ನು ಬರೆಯಿರಿ…",
    speak: "🎤 ಮಾತನಾಡಿ", stop: "⏹ ನಿಲ್ಲಿಸಿ", go: "ನನ್ನ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ", working: "ಯೋಜನೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…",
    profile: "ನಿಮ್ಮ ವಿವರಗಳು", map: "ನಿಮ್ಮ ಅರ್ಹತೆಯ ನಕ್ಷೆ", docs: "ಬೇಕಾಗಬಹುದಾದ ದಾಖಲೆಗಳು",
    status: { ELIGIBLE: "ಅರ್ಹರು", LIKELY_ELIGIBLE: "ಬಹುಶಃ ಅರ್ಹರು", MISSING_INFORMATION: "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ ಬೇಕು", NOT_ELIGIBLE: "ಅರ್ಹರಲ್ಲ" },
    why: "ಏಕೆ?", docsNeeded: "ಅಗತ್ಯ ದಾಖಲೆಗಳು", verify: "ಅಧಿಕೃತ ಮಾಹಿತಿ ಪರಿಶೀಲಿಸಿ ↗", followup: "ಕೆಲವು ಸಣ್ಣ ಪ್ರಶ್ನೆಗಳು",
    aiDown: "AI ಸೇವೆ ತಾತ್ಕಾಲಿಕವಾಗಿ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಇಂಗ್ಲಿಷ್ ಬಳಸಿ.",
  },
  or: {
    title: "ଆପଣ ଯୋଗ୍ୟ ହୋଇପାରୁଥିବା ସରକାରୀ ଯୋଜନା ଖୋଜନ୍ତୁ", chooseLang: "ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ",
    label: "ଆପଣଙ୍କ ଅବସ୍ଥା କୁହନ୍ତୁ", ph: "ଆପଣଙ୍କ ଅବସ୍ଥା ଲେଖନ୍ତୁ…",
    speak: "🎤 କୁହନ୍ତୁ", stop: "⏹ ବନ୍ଦ କରନ୍ତୁ", go: "ମୋ ଯୋଜନା ଖୋଜନ୍ତୁ", working: "ଯୋଜନା ଯାଞ୍ଚ ହେଉଛି…",
    profile: "ଆପଣଙ୍କ ସୂଚନା", map: "ଆପଣଙ୍କ ଯୋଗ୍ୟତାର ମାନଚିତ୍ର", docs: "ଆବଶ୍ୟକ ହୋଇପାରୁଥିବା ଦଲିଲ",
    status: { ELIGIBLE: "ଯୋଗ୍ୟ", LIKELY_ELIGIBLE: "ସମ୍ଭବତଃ ଯୋଗ୍ୟ", MISSING_INFORMATION: "ଅଧିକ ସୂଚନା ଦରକାର", NOT_ELIGIBLE: "ଯୋଗ୍ୟ ନୁହନ୍ତି" },
    why: "କାହିଁକି?", docsNeeded: "ଆବଶ୍ୟକ ଦଲିଲ", verify: "ସରକାରୀ ସୂଚନା ଯାଞ୍ଚ କରନ୍ତୁ ↗", followup: "କିଛି ଛୋଟ ପ୍ରଶ୍ନ",
    aiDown: "AI ସେବା ଅସ୍ଥାୟୀ ଭାବେ ଉପଲବ୍ଧ ନାହିଁ। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ କିମ୍ବା ଇଂରାଜୀ ବ୍ୟବହାର କରନ୍ତୁ।",
  },
  ml: {
    title: "നിങ്ങൾക്ക് യോഗ്യതയുള്ള സർക്കാർ പദ്ധതികൾ കണ്ടെത്തുക", chooseLang: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    label: "നിങ്ങളുടെ സാഹചര്യം പറയുക", ph: "നിങ്ങളുടെ സാഹചര്യം എഴുതുക…",
    speak: "🎤 സംസാരിക്കുക", stop: "⏹ നിർത്തുക", go: "എന്റെ പദ്ധതികൾ കണ്ടെത്തുക", working: "പദ്ധതികൾ പരിശോധിക്കുന്നു…",
    profile: "നിങ്ങളുടെ വിവരങ്ങൾ", map: "നിങ്ങളുടെ യോഗ്യതാ ഭൂപടം", docs: "ആവശ്യമായേക്കാവുന്ന രേഖകൾ",
    status: { ELIGIBLE: "യോഗ്യർ", LIKELY_ELIGIBLE: "ഒരുപക്ഷേ യോഗ്യർ", MISSING_INFORMATION: "കൂടുതൽ വിവരം വേണം", NOT_ELIGIBLE: "യോഗ്യരല്ല" },
    why: "എന്തുകൊണ്ട്?", docsNeeded: "ആവശ്യമായ രേഖകൾ", verify: "ഔദ്യോഗിക വിവരം പരിശോധിക്കുക ↗", followup: "ചില ചെറിയ ചോദ്യങ്ങൾ",
    aiDown: "AI സേവനം താൽക്കാലികമായി ലഭ്യമല്ല. ദയവായി വീണ്ടും ശ്രമിക്കുക അല്ലെങ്കിൽ ഇംഗ്ലീഷ് ഉപയോഗിക്കുക.",
  },
};
